### ISSUE TITLE
DiscoveryRule tests are failing while creating hostgroup in setUpClass

### ISSUE THREAD

**Issue by sghai** [SatelliteQE/nailgun#224]
```
======================================================================
ERROR: test suite for <class 'tests.foreman.api.test_discoveryrule.DiscoveryRule'>
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 208, in run
    self.setUp()
  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 291, in setUp
    self.setupContext(ancestor)
  File "/usr/lib/python2.7/site-packages/nose/suite.py", line 314, in setupContext
    try_run(context, names)
  File "/usr/lib/python2.7/site-packages/nose/util.py", line 469, in try_run
    return func()
  File "/home/sghai/QE/robottelo/tests/foreman/api/test_discoveryrule.py", line 17, in setUpClass
    cls.hostgroup = entities.HostGroup().create()
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 1908, in create
    id=self.create_json(create_missing)['id'],
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 1944, in read
    attrs[attr] = attrs2[attr]
KeyError: 'content_source_id'
---
```

**Comment by Ichimonji10** [comment]
Is this running against upstream or downstream? What does the relevant test code look like?

**Comment by sghai** [comment]
Its against running upstream. 

Basically all robotello api tests for DiscoveryRules are failing while creating a HostGroup in `setUpClass` and `read` method of Hostgroup throwing error `KeyError: 'content_source_id'`

**Comment by Ichimonji10** [comment]
NailGun does not currently support upstream.

**Comment by Ichimonji10** [comment]
This issue depends on #214.

**Comment by Ichimonji10** [comment]
Closing because NailGun does not currently support upstream. Please re-open if support is added and this test still fails.
