### ISSUE TITLE
Unable to search Host using just hostname

### ISSUE THREAD

**Issue by san7ket** [SatelliteQE/nailgun#421]
Name: nailgun
Version: 0.29.0

```
apple=entities.Host(server_config
).search(query={'search' : 'name=aimee-vietzke.satellie.com'})
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-155-c0313b18d12a>", line 2, in <module>
    ).search(query={'search' : 'name=aimee-vietzke.host.centralci.eng.rdu2.redhat.com'})
  File "/usr/lib/python2.7/site-packages/blinker_herald/base.py", line 137, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 1320, in search
    for result in results
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 2636, in __init__
    super(Host, self).__init__(server_config, **kwargs)
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 413, in __init__
    self._server_config
  File "/usr/lib/python2.7/site-packages/nailgun/entity_mixins.py", line 136, in _make_entity_from_id
    return entity_cls(server_config, id=entity_obj_or_id)
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 3050, in __init__
    _check_for_value('compute_resource', kwargs)
  File "/usr/lib/python2.7/site-packages/nailgun/entities.py", line 152, in _check_for_value
    'A value must be provided for the "{0}" field.'.format(field_name)
TypeError: A value must be provided for the "compute_resource" field.
```
While, 
https://satellite.com/api/hosts?search=name=aimee-vietzk.satellite.com successfully returns the result

**Comment by san7ket** [comment]
PR is merged
