### ISSUE TITLE
Unable to get all repositories for an organization

### ISSUE THREAD

**Issue by martin-schlossarek** [SatelliteQE/nailgun#457]
I'm trying to get all repositories for one particular organization with nailgun 0.30.1:

```python
>>> import nailgun.config
>>> import nailgun.entities
>>> url = "https://satellite6.mycompany.com"
>>> username = "admin"
>>> password = "password"
>>> server_config = nailgun.config.ServerConfig(url=url, auth=(username, password))
>>> repositories = nailgun.entities.Repository(server_config, organization_id=1).search()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entities.py", line 4862, in __init__
    super(Repository, self).__init__(server_config, **kwargs)
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 399, in __init__
    .format(self._fields.keys(), kwargs.keys())
nailgun.entity_mixins.NoSuchFieldError: Valid fields are dict_keys(['backend_identifier', 'checksum_type', 'content_counts', 'content_type', 'container_repository_name', 'docker_upstream_name', 'download_policy', 'gpg_key', 'label', 'last_sync', 'mirror_on_sync', 'name', 'product', 'unprotected', 'url', 'id']), but received dict_keys(['organization_id']) instead.
```

Seems that the organization_id field is missing. Lets try it without organization_id:

```python
>>> repositories = nailgun.entities.Repository(server_config).search()

WARNING:nailgun.client:Received HTTP 404 response: {"displayMessage":"One of parameters [ organization_id ] required but not specified.","errors":["One of parameters [ organization_id ] required but not specified."]}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/blinker_herald/base.py", line 137, in wrapper
    result = fn(*args, **kwargs)
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1358, in search
    results = self.search_json(fields, query)['results']
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1210, in search_json
    response.raise_for_status()
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://satellite6.mycompany.com/katello/api/v2/repositories
```

Strange.

**Comment by svtkachenko** [comment]
Interesting, what version of the server you are using? Because I do not see second message.
Also,

1) Nailgun does not support raw API fields it rather use its own representation. Where it is supported you can provide either nailgun's object `Organization` or simply id but field will be called `organization`, like 
```python
In [22]: entities.Product(conf, organization=1).search()
Out[22]: [nailgun.entities.Product(gpg_key=None, description=None, label=u'XygkChTzuOV', 
```
or 
```python
org = entities.Organization(id=1).read()
entities.Product(organization=org).search() 
```
However, in case of `entities.Repository` this field is missing but it does not matter because of p. 3

2) Because of API limitations/inonsistency it is not always working and you can use raw search query:
```python
In [31]: entities.Host(conf, organization=1).create(create_missing=True)
Out[31]: nailgun.entities.Host(comment=None, domain=nailgun.entities.Domain(id=39), managed=True, ip=None, image=None, provision_method=u'build', hostgroup=None, owner=nailgun.entities.User(id=3), operatingsystem=nailgun.entities.OperatingSystem(id=40), subnet=None, realm=None, capabilities=[u'build'], id=42, environment=nailgun.entities.Environment(id=39), build=False, host_parameters_attributes=[], puppet_ca_proxy=None, ptable=nailgun.entities.PartitionTable(id=166), location=nailgun.entities.Location(id=82), medium=nailgun.entities.Media(id=46), puppetclass=[], compute_profile=None, mac=u'f6:7e:90:26:e1:48', interface=[nailgun.entities.Interface(host=nailgun.entities.Host(id=42), id=50)], puppet_proxy=None, owner_type=u'User', name=u'ifrdthqx.givrb8971p', enabled=True, compute_resource=None, architecture=nailgun.entities.Architecture(id=40), all_parameters=[], organization=nailgun.entities.Organization(id=1), model=None)

In [32]: entities.Host(conf).search(query={'search': 'organization_id=1'})
Out[32]: [nailgun.entities.Host(comment=None, domain=nailgun.entities.Domain(id=39), managed=True, ip=None, image=None, provision_method=u'build', compute_resource=None, owner=nailgun.entities.User(id=3), id=42, subnet=None, realm=None, capabilities=[u'build'], operatingsystem=nailgun.entities.OperatingSystem(id=40), environment=nailgun.entities.Environment(id=39), location=nailgun.entities.Location(id=82), puppet_ca_proxy=None, ptable=nailgun.entities.PartitionTable(id=166), build=False, medium=nailgun.entities.Media(id=46), compute_profile=None, mac=u'f6:7e:90:26:e1:48', puppet_proxy=None, owner_type=u'User', name=u'ifrdthqx.givrb8971p', enabled=True, hostgroup=None, architecture=nailgun.entities.Architecture(id=40), organization=nailgun.entities.Organization(id=1), model=None)]
```

3) Looks like this kind of search is not supported by API itself:
```python
In [33]: entities.Repository(conf).search_json(query={'search': 'organization_id=1'})
Out[33]: 
{u'error': u"Field 'organization_id' not recognized for searching!",
 u'page': None,
 u'per_page': None,
 u'results': [],
 u'search': u'organization_id=1',
 u'sort': {u'by': None, u'order': None},
 u'subtotal': None,
 u'total': 31}
```

**Comment by martin-schlossarek** [comment]
We are using Satellite 6.2.12.

I also tried:
```python
>>> nailgun.entities.Repository(server_config, organization=1).search()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/t7.lan.tuhuk.de/sy077/.local/share/virtualenvs/huk-satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entities.py", line 4862, in __init__
    super(Repository, self).__init__(server_config, **kwargs)
  File "/home/t7.lan.tuhuk.de/sy077/.local/share/virtualenvs/huk-satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 399, in __init__
    .format(self._fields.keys(), kwargs.keys())
nailgun.entity_mixins.NoSuchFieldError: Valid fields are dict_keys(['backend_identifier', 'checksum_type', 'content_counts', 'content_type', 'container_repository_name', 'docker_upstream_name', 'download_policy', 'gpg_key', 'label', 'last_sync', 'mirror_on_sync', 'name', 'product', 'unprotected', 'url', 'id']), but received dict_keys(['organization']) instead.
```
But without success.

Also tried raw search query:
```python
>>> nailgun.entities.Repository(server_config).search(query={'search': 'organization_id=1'})
WARNING:nailgun.client:Received HTTP 404 response: {"displayMessage":"One of parameters [ organization_id ] required but not specified.","errors":["One of parameters [ organization_id ] required but not specified."]}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/blinker_herald/base.py", line 137, in wrapper
    result = fn(*args, **kwargs)
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1358, in search
    results = self.search_json(fields, query)['results']
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1210, in search_json
    response.raise_for_status()
  File "/home/mycompany.com/user/.local/share/virtualenvs/satellite6-scripts-jdgpTG3X/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://satellite6.mycompany.com/katello/api/v2/repositories
```

If I try it with curl...
```bash
$ curl https://satellite6.mycompany.com/katello/api/v2/repositories/?organization_id=1 -s -u admin:$(cat /root/adminpw) | python -m "json.tool"
{
    "total": 52,
    "subtotal": 52,
    "page": 1,
    "per_page": 20,
    "error": null,
    "search": null,
    "sort": {
        "by": null,
        "order": null
    },
    "results": [
        {
...
```

**Comment by sean797** [comment]
I'm getting the same issue, it seem reverting https://github.com/SatelliteQE/nailgun/pull/439 fixed it for me. 

A nice easy way to reproduce this is using the `katello_repository_set` module in https://github.com/theforeman/foreman-ansible-modules

First time it will work (and enable the repo, the second time it will fail) 
```yaml
- hosts: localhost
  tasks:
  - name: Load server config
    include_vars:
      file: server_vars.yml
  - name: "Enable RHEL 7 RPMs repositories"
    katello_repository_set:
      username: "{{ foreman_username }}"
      password: "{{ foreman_password }}"
      server_url: "{{ foreman_server_url }}"
      verify_ssl: "{{ foreman_verify_ssl }}"
      name: "Red Hat Enterprise Linux 7 Server (RPMs)"
      organization: "Default Organization"
      product: "Red Hat Enterprise Linux Server"
      state: 'enabled'
      repositories:
      - releasever: "7.0"
        basearch: "x86_64"
```

**Comment by rochacbruno** [comment]
Note that nsilgun has another branch for `6.2` systems: https://github.com/SatelliteQE/nailgun/tree/6.2.z and this branch is frozen at 0.27.0 (pypi version).

I recommend installing from git 

```bash
pip install https://github.com/SatelliteQE/nailgun/tarball/6.2.z
```

**Comment by sean797** [comment]
Thanks @rochacbruno i think this can be closed, using the correct branch "Works for me" 👍
