### ISSUE TITLE
Subscritpion.read() failing because of system filed having "host_id" instead of "id"

### ISSUE THREAD

**Issue by renzon** [SatelliteQE/nailgun#475]
6.2.z branch

Example:

```python
    subs = Subscription(cfg, organization=1).search()[0]
    print(subs.read())
```
Result
```console
Traceback (most recent call last):
  File "/home/renzo/PycharmProjects/nailgun/nailgun/entities.py", line 5704, in <module>
    print(subs.read())
  File "/home/renzo/PycharmProjects/nailgun/nailgun/entities.py", line 5167, in read
    return super(Subscription, self).read(entity, attrs, ignore)
  File "/home/renzo/PycharmProjects/nailgun/nailgun/entity_mixins.py", line 808, in read
    in _get_entity_ids(field_name, attrs)
  File "/home/renzo/PycharmProjects/nailgun/nailgun/entity_mixins.py", line 284, in _get_entity_ids
    return [entity['id'] for entity in attrs[plural_field_name]]
KeyError: 'id'
```

**Comment by san7ket** [comment]
PR was merged closing this
