### ISSUE TITLE
cannot update entity_fields.ListField to None

### ISSUE THREAD

**Issue by alda519** [SatelliteQE/nailgun#607]
entity_fields.ListField cannot be updated to None because
https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L207-L208
nailgun tries to iterate over it

```
>>> r = entities.Repository(id=12).read()
>>> r.docker_tags_whitelist is None
True
>>> r.update() # update fails when docker_tags_whitelist is None
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/blinker_herald/base.py", line 137, in wrapper
    result = fn(*args, **kwargs)
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1066, in update
    return self.read(attrs=self.update_json(fields))
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1041, in update_json
    response = self.update_raw(fields)
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1023, in update_raw
    self.update_payload(fields),
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 1008, in update_payload
    return _payload(self.get_fields(), values)
  File "/home/adujicek/git/robottelo/env/lib/python3.6/site-packages/nailgun/entity_mixins.py", line 213, in _payload
    parse(obj) for obj in values[field_name]]
TypeError: 'NoneType' object is not iterable

>>> r.docker_tags_whitelist = ['fee']
>>> r.update()
>>> r = entities.Repository(id=12).read()
>>> r.docker_tags_whitelist
['fee']
```

for example this test fails because of that
`tests/foreman/api/test_docker.py::DockerRepositoryTestCase::test_positive_update_name`

**Comment by alda519** [comment]
patch?
```
diff --git a/nailgun/entity_mixins.py b/nailgun/entity_mixins.py
index 64263bc..b17f420 100644
--- a/nailgun/entity_mixins.py
+++ b/nailgun/entity_mixins.py
@@ -204,7 +204,7 @@ def _payload(fields, values):
                         return _payload(obj.get_fields(), obj.get_values())
                     return obj
 
-                values[field_name] = [
+                values[field_name] = None if values[field_name] is None else [
                     parse(obj) for obj in values[field_name]]
     return values
 
```
