### ISSUE TITLE
getting "flake8.exceptions.InvalidSyntax: TokenError: EOF in multi-line statement" error while running 'make lint'

### ISSUE THREAD

**Issue by jameerpathan111** [SatelliteQE/nailgun#628]
I am trying to setup a development environment and was following nailgun documentation for the same. 
`$ pip install -r requirements.txt -r requirements-dev.txt`
completed successfully.
```
$ make lint
flake8 --ignore=W504,E731 .
Traceback (most recent call last):
  File "/home/jpathan/projects/nailgun/env-nailgun27/bin/flake8", line 10, in <module>
    sys.exit(main())
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/main/cli.py", line 18, in main
    app.run(argv)
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/main/application.py", line 394, in run
    self._run(argv)
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/main/application.py", line 382, in _run
    self.run_checks()
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/main/application.py", line 301, in run_checks
    self.file_checker_manager.run()
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/checker.py", line 328, in run
    self.run_parallel()
  File "/home/jpathan/projects/nailgun/env-nailgun27/lib/python2.7/site-packages/flake8/checker.py", line 292, in run_parallel
    for ret in pool_map:
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 286, in <genexpr>
    return (item for chunk in result for item in chunk)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 655, in next
    raise value
flake8.exceptions.InvalidSyntax: TokenError: EOF in multi-line statement
make: *** [lint] Error 1

```
can someone tell me why I am getting this error and what I have to do to resolve it?

**Comment by vijay8451** [comment]
@jameerpathan111 Could you try to use virtual env using python3.6 ?

**Comment by jameerpathan111** [comment]
> @jameerpathan111 Could you try to use virtual env using python3.6 ?
@vijay8451 
I tried this withvirtual environment of python2.7, python3.4, python3.6 and python3.7 but I am getting same error for all of them.

**Comment by ntkathole** [comment]
@jameerpathan111 you must be using some installed python2 module. Please do 
`pip uninstall -r requirements.txt -r requirements-dev.txt` first and re-try.

**Comment by mirzal** [comment]
Error like that happens when some instruction is opened, but not closed before end of file. Usually it's matter of missing quote delimiter (`'`, `"` or `"""`).

I would blame error in one of modules you installed. Can you try:

```
flake8 --ignore=W504,E731 --exclude=env-nailgun27 .
```

Or remove your virtualenv directory and re-create it outside of nailgun directory.

I could not reproduce it on commit c36d8c20862e87bf6975bd48ac1ca40a9e634eaa, 
```
$ flake8 --version
3.7.7 (mccabe: 0.6.1, pycodestyle: 2.5.0, pyflakes: 2.1.1) CPython 2.7.5 on Linux
```

**Comment by jameerpathan111** [comment]
> Or remove your virtualenv directory and re-create it outside of nailgun directory.

thanks @mirzal  it worked. :+1: 
thanks @vijay8451 @ntkathole
